Add repositories and pluginRepositories to pom.xml
DANS-KNAW/course-scala pull request #20
Opened 2016-11-21 18:49 UTC by rvanheest

@wilkos-dans and I came to this after it did not work for him. @janvanmansum, you forgot to add that this morning!

2016-11-21 18:53 UTC, rvanheest commented
To be honest, I don't think we should actually add the Dans dependencies. This also requires to add the mirror to the `.m2/settings.xml`

2016-11-21 19:56 UTC, rvanheest commented
Could you also add this project to Travis to avoid problems like this in the future?

2016-11-22 09:57 UTC, janvanmansum requested changes

2016-11-22 09:57 UTC, janvanmansum commented on pom.xml
> +    <repositories>
Good point, only it should be:
```
 <repositories>
        <repository>
            <id>DANS</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <url>http://maven.dans.knaw.nl/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>DANS</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <url>http://maven.dans.knaw.nl/</url>
        </pluginRepository>
    </pluginRepositories>
```
Those are accessible from outside the DANS network.

2016-11-22 09:58 UTC, janvanmansum commented on pom.xml
> +    <repositories>
While you are at it you might also add the travis config.

2016-11-22 13:25 UTC, rvanheest commented
Closing this PR for now. Moved these changes to the other PR at #21.
@janvanmansum I added the travis link in #21, but I think you have to add it to travis yourself. I don't have those rights, if I remember correctly.

2016-11-22 13:25 UTC, closed without merging